Repository AY2122S1-CS2103T-F13-3/tp, pull requests merged in 2021-10, with the labels that each got.

#38 Add optional fields school and acad streams
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LessonAddCommand.java
  src/main/java/seedu/address/logic/commands/LessonDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/AcadStream.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Fee.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/School.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Story

#42 Add academic level as an optional field in add and edit commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LessonAddCommand.java
  src/main/java/seedu/address/logic/commands/LessonDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AcadLevel.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Story

#124 Refactoring and formatting to follow coding standards
  src/main/java/seedu/address/logic/commands/LessonAddCommand.java
  src/main/java/seedu/address/logic/commands/LessonDeleteCommand.java
  src/main/java/seedu/address/logic/parser/LessonDeleteCommandParser.java
  src/main/java/seedu/address/model/lesson/Date.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/MakeUpLesson.java
  src/main/java/seedu/address/model/lesson/RecurringLesson.java
  src/main/java/seedu/address/model/lesson/TimeRange.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task

#119 Update UG for Lesson Add
  docs/UserGuide.md
Labels: type.UG

#142 Update DG for Undo/Redo Implementation
  docs/DeveloperGuide.md
  docs/diagrams/LessonAddSequenceDiagram.puml
  docs/diagrams/LessonDeleteSequenceDiagram.puml
  docs/diagrams/LessonEditSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/UndoableCommandInheritance.puml
  docs/images/LessonAddSequenceDiagram.png
  docs/images/LessonDeleteSequenceDiagram.png
  docs/images/LessonEditSequenceDiagram.png
  docs/images/UndoRedoStack1CommandDiagram.png
  docs/images/UndoRedoStack1UndoDiagram.png
  docs/images/UndoRedoStackStartDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/UndoableCommandInheritance.png
  src/main/java/seedu/address/logic/UndoRedoStack.java
  src/test/java/seedu/address/logic/UndoRedoStackTest.java
  src/test/java/seedu/address/logic/UndoRedoStackTestUtil.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandIntegrationTest.java
Labels: priority.High, type.DG

#164 Update glossary for ug
  docs/UserGuide.md
Labels: priority.High, type.UG

#163 Update user guide for ui, help and tag.
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/images/macSecurity.png
  docs/images/taglist.png
Labels: priority.High, type.UG

#250 Fix edit start date bug for makeup lesson
  src/main/java/seedu/address/logic/commands/LessonAddCommand.java
  src/main/java/seedu/address/logic/commands/LessonEditCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/CalendarEntryList.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditLessonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/LessonAddCommandTest.java
  src/test/java/seedu/address/logic/commands/LessonEditCommandTest.java
Labels: priority.High, severity.High
