Repository AY2122S1-CS2103T-F13-3/tp, pull requests merged in 2021-09, with the labels that each got.

#69 Developers Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.DG

#76 Update UG Quick Start
  docs/UserGuide.md
Labels: type.Bug, priority.High, type.UG

#73 Update UG Find and Filter
  docs/UserGuide.md
Labels: type.UG

#82 Add UG fields for add and edit command and improve phrasing and formatting
  docs/UserGuide.md
Labels: type.UG

#65 Update UG
  docs/UserGuide.md
  docs/images/viewAlexDetail.png
Labels: priority.High, type.UG

#91 UG update command summary table
  docs/UserGuide.md
Labels: priority.High, type.UG

#90 UG reorganise features
  docs/UserGuide.md
Labels: priority.High, type.UG

#96 Fix UG formatting and language
  docs/UserGuide.md
Labels: priority.High, type.UG

#97 Use TAB instead of address book in UG
  docs/UserGuide.md
Labels: priority.High, type.UG
