Repository AY2122S1-CS2103T-F13-3/tp, pull requests merged in 2021-11, with the labels that each got.

#227 Wrap text for long tag name in taglist & Fix lesson panel with long name
  src/main/java/seedu/address/logic/commands/LessonEditCommand.java
  src/main/java/seedu/address/model/lesson/CalendarEntryList.java
  src/main/java/seedu/address/model/person/PersonMatchesKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/LessonListPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TagCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LessonListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonGridPanel.fxml
  src/main/resources/view/ReminderLessonCard.fxml
  src/main/resources/view/TagListCard.fxml
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, severity.Medium

#276 Fix Undo/Redo Bugs
  src/main/java/seedu/address/logic/UndoRedoStack.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LessonAddCommand.java
  src/main/java/seedu/address/logic/commands/LessonDeleteCommand.java
  src/main/java/seedu/address/logic/commands/LessonEditCommand.java
  src/main/java/seedu/address/logic/commands/PaidCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/UndoRedoStackTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/LessonEditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandIntegrationTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, priority.High

#335 Add check for invalid date range on storage load
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/test/java/seedu/address/storage/JsonAdaptedLessonTest.java
Labels: type.Bug, severity.Medium

#345 Filter empty tags and homework
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedHomework.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: type.Bug

#348 Update FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug, severity.Medium

#309 Update UG with Command Format guide
  docs/UserGuide.md
  docs/images/CommandFormat.png
Labels: type.UG

#334 Section command summary
  docs/UserGuide.md
Labels: type.UG

#317 [UG] Add annotated GUI info and format student fields table
  docs/Gemfile
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/annotatedFileStorage.png
  docs/images/annotatedGui.png
  docs/images/annotatedMakeupLessonCard.png
  docs/images/annotatedRecurringLessonCard.png
  docs/images/annotatedStudentCard.png
  docs/images/findAll.png
  docs/images/findNone.png
  docs/images/help.png
  docs/images/remind.png
  docs/images/start.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.UG

#314 Clarify redo conditions and Fees Calc Behaviour in UG
  docs/Gemfile
  docs/Gemfile.lock
  docs/UserGuide.md
  src/main/java/seedu/address/logic/FeesCalculator.java
Labels: type.UG

#307 Update UG command parameters for Lesson
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/LessonAddCommand.java
Labels: priority.High, type.UG

#351 [UG] Reformat find notes
  docs/UserGuide.md
  docs/images/find.PNG
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.UG

#360 Fix broken link
  docs/UserGuide.md
Labels: type.Bug, type.UG

#373 UG improve About This Guide
  docs/UserGuide.md
Labels: type.UG

#371 Update diagrams
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LessonAddLogicSequenceDiagram.puml
  docs/diagrams/LessonAddSequenceDiagram.puml
  docs/diagrams/LessonDeleteSequenceDiagram.puml
  docs/diagrams/LessonEditLogicSequenceDiagram.puml
  docs/diagrams/LessonEditSequenceDiagram.puml
  docs/images/LessonAddLogicSequenceDiagram.png
  docs/images/LessonAddSequenceDiagram.png
  docs/images/LessonEditSequenceDiagram.png
Labels: type.DG

#359 [DG] Update find command and add Cancelled Dates
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindUpdateFilteredListLogicSequenceDiagram.puml
  docs/diagrams/Lesson.puml
  docs/images/FindSequenceDiagram.png
  docs/images/FindUpdateFilteredListLogicSequenceDiagram.png
  docs/images/Lesson.png
  docs/images/LessonClassDiagram.png
  docs/images/RecurringCalendarEntries.png
Labels: type.DG

#375 Update effort section for lessons
  docs/DeveloperGuide.md
Labels: type.DG

#378 DG improve manual testing
  docs/DeveloperGuide.md
Labels: type.DG

#374 Link back to parameters
  docs/UserGuide.md
Labels: priority.Low, type.UG

#384 [UG] Step by step for add student
  docs/UserGuide.md
  docs/images/add1.png
  docs/images/add2.png
Labels: priority.Low, type.UG

#372 Add step by step examples for ladd and ledit
  docs/UserGuide.md
  docs/images/laddExample.png
  docs/images/leditExample.png
Labels: priority.Low, type.UG

#376 CS2101 UG improvements
  docs/UserGuide.md
  docs/images/EditCommandEditBetsyInitial.png
  docs/images/EditCommandEditBetsyResult.png
Labels: priority.Low, type.UG
